name: notion
version: 0.1.0.0
synopsis: Unofficial Notion Haskell Client
maintainer: Deniz Alp Durmaz <denizalpd@ogr.iu.edu.tr>
category: Web
license: BSD3
ghc-options: -Wall -O2 -fspecialise-aggressively

default-extensions:
  - DataKinds
  - DerivingStrategies
  - FlexibleContexts
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies  

extra-source-files:
  - README.md

library:
  source-dirs:
    - src
  dependencies:  
    - aeson
    - base
    - containers
    - http-client
    - http-client-tls
    - lens
    - load-env
    - servant
    - servant-client
    - text
    - time
    - tls
    - uuid
    - uri-bytestring
